/**
 * Convert docs/logo.png to a PNG byte array for G2 glasses welcome screen.
 * Composites the logo + "tap to enter" subtitle into a single image.
 * The Even App host converts PNG to monochrome automatically.
 *
 * Run once:  npx tsx scripts/convert-logo.ts
 * Outputs:   g2/logo-data.ts  (PNG as number[])
 *
 * G2 image container max: 288w x 144h.
 */
import sharp from 'sharp'
import { writeFileSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = resolve(__dirname, '..')

// G2 image container max: 200w x 100h (per even-g2-notes docs)
const IMG_W = 200
const IMG_H = 100
const LOGO_H = 78
const TEXT_H = IMG_H - LOGO_H

async function main() {
  // Source logo: dark artwork on light beige background
  // G2: bright pixels = green, dark pixels = off
  // Strategy: threshold to pure black/white, then negate so artwork is bright
  const logoImg = await sharp(resolve(root, 'docs/logo.png'))
    .resize(IMG_W, LOGO_H, { fit: 'contain', background: { r: 255, g: 255, b: 255 } })
    .flatten({ background: { r: 255, g: 255, b: 255 } })
    .grayscale()
    .threshold(180) // binarize: light bg -> white, dark artwork -> black
    .negate()       // invert: artwork becomes white (green on G2), bg becomes black (off)
    .png()
    .toBuffer()

  const subtitleSvg = Buffer.from(`<svg width="${IMG_W}" height="${TEXT_H}">
    <style>text { font-family: sans-serif; font-size: 16px; font-weight: bold; fill: #fff; }</style>
    <text x="50%" y="55%" text-anchor="middle" dominant-baseline="middle">tap to enter</text>
  </svg>`)
  const subtitleImg = await sharp(subtitleSvg).png().toBuffer()

  // Composite on black canvas, convert to greyscale PNG
  const pngBuf = await sharp({
    create: { width: IMG_W, height: IMG_H, channels: 3, background: { r: 0, g: 0, b: 0 } },
  })
    .composite([
      { input: logoImg, top: 0, left: 0 },
      { input: subtitleImg, top: LOGO_H, left: 0 },
    ])
    .grayscale()
    .png()
    .toBuffer()

  // Export as number[] (same format Tesla app uses for map tiles)
  const bytes = Array.from(new Uint8Array(pngBuf))

  const out = `// Auto-generated by scripts/convert-logo.ts - do not edit
export const LOGO_W = ${IMG_W}
export const LOGO_H = ${IMG_H}
export const LOGO_PNG: number[] = [${bytes.join(',')}]
`

  const outPath = resolve(root, 'g2/logo-data.ts')
  writeFileSync(outPath, out)
  console.log(`Wrote ${outPath} (${IMG_W}x${IMG_H}, ${bytes.length} bytes PNG)`)
}

main().catch((e) => { console.error(e); process.exit(1) })
